# Generated by Django 4.2.6 on 2023-12-16 12:15

import ads.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='стоимость')),
                ('transaction_type', models.CharField(choices=[('debit', 'Списание'), ('credit', 'Зачисление')], max_length=10, verbose_name='тип транзакции')),
            ],
            options={
                'verbose_name': 'История объявлений',
                'verbose_name_plural': 'Истории объявлений',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('title', models.CharField(max_length=120, verbose_name='наименование')),
                ('description', models.CharField(max_length=120, verbose_name='описание')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Активен'), (1, 'Выполняется'), (2, 'Выполнен')], default=0, verbose_name='статус')),
                ('image', models.ImageField(blank=True, default=ads.models.Ads.default_poster, null=True, upload_to='adsImage', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'], message='Извините, этот формат файла не поддерживается')], verbose_name='изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
            },
        ),
    ]
