# Generated by Django 4.2.6 on 2023-12-16 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='acting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acting_ads', to='bank.client', verbose_name='исполнитель'),
        ),
        migrations.AddField(
            model_name='ads',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_ads', to='bank.client', verbose_name='заказчик'),
        ),
        migrations.AddField(
            model_name='adhistory',
            name='ads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ads.ads', verbose_name='объявление'),
        ),
        migrations.AddField(
            model_name='adhistory',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bank.client', verbose_name='чье объявление?'),
        ),
    ]
