# Generated by Django 4.2.6 on 2023-12-16 12:15

import auths.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('datetime_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('first_name', models.CharField(max_length=40, verbose_name='имя')),
                ('last_name', models.CharField(max_length=40, verbose_name='фамилия')),
                ('email', models.CharField(max_length=60, unique=True, verbose_name='почта/логин')),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='пароль1')),
                ('password2', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='пароль2')),
                ('avatar', models.ImageField(blank=True, default=auths.models.User.default_poster, upload_to='posters', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'], message='Извините, этот формат файла не поддерживается')], verbose_name='постер')),
                ('is_active', models.BooleanField(default=False, verbose_name='активный?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='это персонал')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперпользователь')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ('datetime_created',),
            },
        ),
        migrations.CreateModel(
            name='TokenList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('refresh_token', models.CharField(max_length=300, null=True, verbose_name='Токен')),
                ('expire_datetime', models.DateTimeField(verbose_name='Время истечения токена')),
                ('user', models.ForeignKey(help_text='Связанный пользователь', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'список токена',
                'verbose_name_plural': 'список токенов',
                'ordering': ('expire_datetime',),
            },
        ),
        migrations.CreateModel(
            name='AccountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.PositiveSmallIntegerField(choices=[(1, 'ACCOUNT-ACTIVATION'), (2, 'PASSWORD-RESET')], default=1, verbose_name='тип кода')),
                ('code', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='код')),
                ('datetime_expire', models.DateTimeField(verbose_name='время окончания действия кода')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activate_account_codes', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'код активации',
                'verbose_name_plural': 'коды активации',
                'ordering': ('datetime_expire',),
            },
        ),
    ]
