# Generated by Django 4.2.6 on 2023-12-09 11:12

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('base_currency', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='базовая валюта')),
                ('target_currency', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='конвертируемая валюта')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='итог')),
            ],
            options={
                'verbose_name': 'Обменный курс',
                'verbose_name_plural': 'Обменные курсы',
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='card',
            name='date_expiration',
            field=models.DateField(default=datetime.datetime(2024, 12, 8, 17, 12, 14, 350942), verbose_name='дата истечения'),
        ),
    ]
