# Generated by Django 4.2.6 on 2023-12-10 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_expiration',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 11, 0, 16, 903097), verbose_name='дата истечения'),
        ),
    ]
