# Generated by Django 4.2.6 on 2023-12-09 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_exchangerate_alter_card_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_expiration',
            field=models.DateField(default=datetime.datetime(2024, 12, 8, 17, 13, 20, 785467), verbose_name='дата истечения'),
        ),
    ]
